In [1]:
# dataframe create using list:

In [2]:
data =[12,89,3,8,0]

In [3]:
import pandas as pd

In [6]:
df = pd.DataFrame(data,columns=['Age'])

In [7]:
print(df)

   Age
0   12
1   89
2    3
3    8
4    0

In [8]:
df['Age']

0    12
1    89
2     3
3     8
4     0
Name: Age, dtype: int64

In [16]:
df['Age'].iloc[2]=4

/tmp/ipykernel_10747/1948711858.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Age'].iloc[2]=4

In [17]:
df

    Age
0   1.0
1  89.0
2   4.0
3   8.0
4   0.0
1   1.0

In [18]:
# Dataframe using dict

In [20]:
data={
    'name':['oo','aa'],
    'age':[129,0]
}

In [21]:
df=pd.DataFrame(data)

    name    age
0  False  False
1  False  False

In [25]:
df.notnull()

   name   age
0  True  True
1  True  True